# Generated by Django 4.2.5 on 2024-06-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Women', 'Женское'), ('Men', 'Мужское')], max_length=20),
        ),
    ]
