# Generated by Django 4.2.5 on 2024-06-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Men', 'Мужское'), ('Women', 'Женское')], max_length=20),
        ),
    ]
