# Generated by Django 5.0.2 on 2024-02-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userinfo_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='images',
            field=models.ImageField(default='avatars/ER.png', upload_to='avatars/'),
        ),
    ]
