# Generated by Django 4.2.5 on 2024-03-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userinfo_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='images',
            field=models.ImageField(upload_to='avatars/'),
        ),
    ]
