# Generated by Django 4.2.5 on 2024-06-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='cart',
        ),
        migrations.AddField(
            model_name='basket',
            name='cart',
            field=models.ManyToManyField(related_name='baskets', to='shop_content.cartitem'),
        ),
    ]
